#pragma kernel KernelFunction_A
#pragma kernel KernelFunction_B

RWStructuredBuffer<float> floatBuffer;
float floatValue;

[numthreads(4,1,1)]
void KernelFunction_A(uint3 groupID : SV_GroupID, uint3 groupThreadID : SV_GroupThreadID )
{
    floatBuffer[groupThreadID.x] = float(groupThreadID.x) * floatValue;
}

[numthreads(4,1,1)]
void KernelFunction_B(uint3 groupID : SV_GroupID, uint3 groupThreadID : SV_GroupThreadID)
{
    floatBuffer[groupThreadID.x] += 1.0f;
}